### PR TITLE
Add support for OAuth2 token authentication, bump version to 0.5.0

### PR DESCRIPTION
**Pull request by Lekensteyn**
Implement OAuth2 Token Authentication based on
https://docs.docker.com/registry/spec/auth/oauth/. This is an
alternative to classic JWT Token Authentication that may require a
username and password.

This adds support for our internal Docker Registry which does not
support the JWT token interface (`GET /auth?service=...&scope=...`).

### CODE REVIEW

**Comment by stesie** [comment]
LGTM

I wonder whether we should mention OAuth2 authentication in readme as well (as opposed to changelog only), including OAuth2 authentication can only be used by using auth config from docker.

However I suppose that, now we can use said auth config, users will no longer want to provide credentials on command line anyhow

**Comment by DirtyHairy** [comment]
Thanks alot for your contribution! I'll add a few words to the readme and release.

**Comment by Lekensteyn** [comment]
If `docker-ls` options to control credentials are deprecated in favour of Docker-supplied credentials, it could potentially affect people that use `docker-ls` without having Docker configured and running. Not sure how many people do that though.

The README does mention that Docker-style token authentication is supported, wouldn't that be sufficient?

Looking forward to the next release :-)

[alot](https://hyperboleandahalf.blogspot.com/2010/04/alot-is-better-than-you-at-everything.html)

**Comment by DirtyHairy** [comment]
> If docker-ls options to control credentials are deprecated in favour of Docker-supplied credentials,

They're still supported, and they're not going anywhere, we just assume that they won't be widely used anymore. We absolutely do not want to break existing workflows without a very good reason 😏 

>Looking forward to the next release :-)

[Already done](https://github.com/mayflower/docker-ls/releases/tag/v0.5.0) 😛 

Thanks again for contributing!

**Comment by Lekensteyn** [comment]
Oh it looks like the tag was pushed, but commit 0eb4c9ab7f04f48dadd9e32aecace4a7da2270e5 is not on master.

**Comment by DirtyHairy** [comment]
...and of course you're right 😏 Done.

**Pull request merged**
